on:
  issues:
    types:
      - opened

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.issue.user.name }}'
      - run: echo '${{ github.event.sender }}'
