on:
  workflow_dispatch:

jobs:
  bar:
    strategy:
      matrix:
        foo: [1,2,3,4,5,6,7,8,9,10]
        bar: [1,2,3,4,5,6,7,8,9,10]
    runs-on: ubuntu-latest
    steps:
      - run: sudo snap download charmed-postgresql
      - uses: actions/upload-artifact@v4
        with:
          name: bar-${{ matrix.foo }}-${{ matrix.bar }}
          path: curl_debug.log
