on:
  issues:

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.issue.user.login }}'
      - run: echo '${{ github.event.sender.login }}'
      - run: echo '${{ github.actor }}'
